### ISSUE TITLE
Chain Service should provide which Service was used for the returned rate.

### ISSUE THREAD

**Issue by zyglobe** [florianv/exchanger#54]
Related to this issue/request: https://github.com/florianv/swap/issues/110

I'm not sure which approach you might consider.  By using Chain as a Service, we can't inspect or audit which Service was ultimately used for the rate.

  - Changing the design of how a Chain might iterate through Exchangers instead of the other way around seems too big of a change.

  - Having every Service provide a 'hitService' back to the exchanger when it only applies to the Chain service doesn't seem favorable either.

**Comment by florianv** [comment]
@zyglobe I think we need to name services using a string identifier (or we can also use the class name) and add the provider for the rate as a class property

**Comment by florianv** [comment]
FYI, here is the related documentation https://github.com/florianv/exchanger/blob/master/doc/readme.md#rate-provider

**Comment by gmponos** [comment]
Hello.. sorry for saying this but for me the rate as a ValueObject does not add any meaning having the provider...

It would be more interesting providing a solution like 

```
class Chain implements ExchangeRateService
{
    /**
     * Creates a new chain service.
     *
     * @param ExchangeRateService[] $services
     */
    public function __construct(array $services = [], Store $store)
    {
        $this->services = $services;
        $this->store = $store;
    }

        /**
     * {@inheritdoc}
     */
    public function getExchangeRate(ExchangeRateQuery $exchangeQuery): ExchangeRate
    {
        ...
        $this->store->save(whateverobjectisused);
        ....
    }
```

Again the above is an opinionated solution and not the best since you can't be sure that the store will contain the service for the rate A. Therefore I don't believe that a solution like this should exist on the package.. but if someone needs it implement it on their own... It is defenitely better than having it inside the ExchangeRate.

Moreover what happens if I use the `ExchangeRate` as a simple ValueObject without any provider? From a form submit or whatever

**Comment by florianv** [comment]
@gmponos The purpose of this library is to retrieve exchange rates from external services, not to provide a generic exchange rate value object.

In the context of this library, the exchange rate will always be provided by a "service"
