### ISSUE TITLE
Decimal separator in ExchangeRate value

### ISSUE THREAD

**Issue by PhoneixS** [florianv/exchanger#57]
In `getExchangeRate()` from [Forge.php](https://github.com/florianv/exchanger/blob/master/src/Service/Forge.php) you pass the resulted price, which is a float, directly to `ExchangeRate` constructor, then in the `ExchangeRate` constructor you have a cast to `String`:

    $this->value = (string) $value;

This can be problematic as the cast is dependent on the current local as pointed in the [documentation](http://php.net/manual/en/language.types.string.php#language.types.string.casting):

> The decimal point character is defined in the script's locale (category LC_NUMERIC). See the setlocale() function.

In my opinion, it should make a "defined" conversion in which the result is known for example using `number_format`. Or at least, it should be documented in the constructor or the `getValue` method.

In addition, the constructor it's supposed to receive a string, so maybe the Forge service is the one which should make the conversion.

What do you think?

**Comment by florianv** [comment]
Hey @PhoneixS, 

thanks for your issue.

As part of the new major version, I've decided to change the rate values to always return a `float` instead of a string - which solves the issue you are mentioning.

The pull request for the new version is here https://github.com/florianv/exchanger/pull/68 and the code will stay in the `master` branch for a while before a release is made.

Feel free to give your suggestions on it :)
